version: '3.8'

services:
  app:
    build: .
    container_name: Epharmcy
    restart: always
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - laravel

  db:
    image: mariadb:10.4.32
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: app-crud
      MYSQL_USER: root
      MYSQL_PASSWORD: ""  # No password
      MYSQL_ROOT_PASSWORD: ""  # No password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:

volumes:
  db_data:
